obj-y := stdf_main/ stdf_app/ stdf_bsp/ stdf_hal/ stdf_os/ stdf_sdk/

#sdk include

#stdf include
subdir-ccflags-y += \
    -Iconfig/$(T) \
    -Istdf/stdf_main \
    -Istdf/stdf_app \
    -Istdf/stdf_bsp \
    -Istdf/stdf_hal \
    -Istdf/stdf_os \
    -Istdf/stdf_sdk

